### ISSUE TITLE
go-kratos/consul/ 找不到地址

### ISSUE THREAD

**Issue by Ymriri** [feihua/kratos-mall#4]
这个项目 是不是没维护了，运行出现     remote: Repository not found.
        fatal: repository 'https://github.com/go-kratos/consul/' not found

**Comment by feihua** [comment]
近段时间忙。看下是不是新版本路径变了

**Comment by feihua** [comment]
新版本已迁移至目录： https://github.com/go-kratos/kratos/tree/main/contrib/registry/consul
